### <a name='0'></a>Import biblioteki

In [ ]:
import numpy as np

np.__version__

### <a name='1'></a> Ćwiczenie 31
Wykonaj dwa sortowania podanej poniżej tablicy $A$:
* wierszowo (rosnąco)
* kolumnowo (rosnąco)


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.sort()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='2'></a> Ćwiczenie 32
Wytnij wszystkie elementy tablicy $A$ o wartości wyższej niż 8.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='3'></a> Ćwiczenie 33
Podana jest poniższa tablica $A$. Zastąp elementy powyżej wartości 10 wartością stałą 10 (obcięcie wartości do 10).


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.where()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='4'></a> Ćwiczenie 34
Poniższą dwuwymiarową tablicę $A$ przedstaw w postaci 'wypłaszczonej' jednowymiarowej tablicy.  

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Oczekiwany wynik:__


```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Wskazówka:__ Użyj funkcji _np.ravel()_.




In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='5'></a> Ćwiczenie 35
Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 0.0.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Oczekiwany wynik:__


```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```





__Wskazówka:__ Użyj funkcji _np.zeros_like()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='6'></a> Ćwiczenie 36

Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 9.99.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

__Oczekiwany wynik:__


```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```



__Wskazówka:__ Użyj funkcji _np.full_like()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='7'></a> Ćwiczenie 37
Zbuduj tablicę dwuwymiarową (macierz kwadratową dolną trójkątną) podnaną poniżej:


```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Wskazówka:__ Użyj funkcji _np.tri()_.


In [ ]:
# tutaj wpisz rozwiązanie

### <a name='8'></a> Ćwiczenie 38
Stwórz dowolną tablicę 3-wymiarową o kształcie $(2, 3, 4)$.

In [ ]:
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],

              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='9'></a> Ćwiczenie 39

Wygeneruj dwuwymiarową tablicę o kształcie _(200, 300)_ wypełnioną wartościami losowymi od 0 do 255 włacznie i typie danych _np.uint8_ i przypisz do zmiennej _image_.

In [ ]:
# tutaj wpisz rozwiązanie

Nastepnie uruchom poniższy blok kodu. W rezultacie uzyskasz podgląd na losowo wygenerowany czarno-biały obraz.

In [ ]:
!pip install opencv-python

In [ ]:
import cv2
from matplotlib import pyplot as plt
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.show()

### <a name='10'></a> Ćwiczenie 40
Tablicę _image_ z poprzedniego zadania posortuj wzdłuż wiersza rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie

Tablicę _image_ z poprzedniego zadania posortuj wzdłuż kolumny rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie