### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.set_printoptions(suppress=True, precision=4)
np.random.seed(42)
np.__version__

'1.24.4'

### <a name='1'></a> Ćwiczenie 61
Podane są poniższe dwie tablice $A$ i $B$:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```

Wyznacz tablicę składającą się ze średnich arytmetycznych tablic $A$ i $B$ odpowiadających im elementów.

__Oczekiwany wynik:__


```
array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])
```



In [2]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# Rozwiązanie 1
(A + B) / 2

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

In [3]:
# Rozwiązanie 2
np.divide(np.add(A, B), 2)

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

### <a name='2'></a> Ćwiczenie 62
Podane są poniższe dwie tablice $A$ i $B$:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Pomnóż tablice przez siebie - element po elemencie (element-wise).


In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# Rozwiązanie 1
A * B

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

In [5]:
# Rozwiązanie 2
np.multiply(A, B)

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

### <a name='3'></a> Ćwiczenie 63
Podana jest poniższa tablica $A$:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Wyznacz pierwiastek z każdego elementu tablicy $A$.

__Wskazówka:__ Użyj funkcji _np.sqrt()_.



In [6]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

np.sqrt(A)

array([[1.7321, 2.    , 3.    , 1.4142],
       [2.2361, 1.7321, 1.4142, 2.2361]])

### <a name='4'></a> Ćwiczenie 64
Podane są poniższe tablice $A$ oraz $B$:


```
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
```
Sprawdź działanie jedynki trygonometrycznej na tablicy $A$ i następnie porównaj wynik z tablicą $B$. Użyj funkcji _np.allclose()_.

__Jedynka trygonometryczna:__ Dla dowolnej wartości kąta $\alpha \in R$ zachodzi:
$$sin^2\alpha + cos^2\alpha = 1$$



In [7]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

In [8]:
A

array([0.    , 0.0827, 0.1653, 0.248 , 0.3307, 0.4134, 0.496 , 0.5787,
       0.6614, 0.7441, 0.8267, 0.9094, 0.9921, 1.0748, 1.1574, 1.2401,
       1.3228, 1.4054, 1.4881, 1.5708])

In [9]:
np.sin(A) ** 2 + np.cos(A) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [10]:
B

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [11]:
# Rozwiązanie 1
np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B)

True

In [12]:
# Rozwiązanie 2
np.allclose(np.power(np.sin(A), 2) + np.power(np.cos(A), 2), B)

True

### Jedynka trygonometryczna

Jedynka trygonometryczna to fundamentalna tożsamość w trygonometrii, która wyraża podstawową relację między sinusami i cosinusami kątów. Jest to jedno z najważniejszych twierdzeń w trygonometrii, używane do rozwiązywania równań trygonometrycznych i dowodzenia innych tożsamości trygonometrycznych.

#### Definicja

Jedynka trygonometryczna mówi, że dla dowolnego kąta \(\theta\) w układzie współrzędnych:

\[ \sin^2(\theta) + \cos^2(\theta) = 1 \]

Gdzie:
- \(\sin(\theta)\) to sinus kąta \(\theta\),
- \(\cos(\theta)\) to cosinus kąta \(\theta\).

#### Dowód Jedynki Trygonometrycznej

Jedynkę trygonometryczną można dowieść na kilka sposobów. Jednym z najprostszych jest użycie definicji funkcji trygonometrycznych w odniesieniu do trójkąta prostokątnego.

W trójkącie prostokątnym o kącie \(\theta\), przyprostokątne mają długości \(a\) i \(b\), a przeciwprostokątna ma długość \(c\). Funkcje trygonometryczne sinus i cosinus są zdefiniowane jako:

\[ \sin(\theta) = \frac{a}{c} \]
\[ \cos(\theta) = \frac{b}{c} \]

Z twierdzenia Pitagorasa wiemy, że:

\[ a^2 + b^2 = c^2 \]

Podstawiając definicje sinusa i cosinusa, mamy:

\[ \left(\frac{a}{c}\right)^2 + \left(\frac{b}{c}\right)^2 = 1 \]
\[ \sin^2(\theta) + \cos^2(\theta) = 1 \]

#### Przykłady i Zastosowania

Jedynka trygonometryczna jest często używana w matematyce i inżynierii. Oto kilka przykładów jej zastosowania:

1. **Rozwiązywanie równań trygonometrycznych**:
   Równanie \(\sin^2(x) = \cos^2(x)\) można uprościć do \(\sin^2(x) + \cos^2(x) = 1\).

2. **Przekształcanie wyrażeń trygonometrycznych**:
   Można przekształcić wyrażenia takie jak \(\sin^2(x)\) na \(1 - \cos^2(x)\) lub odwrotnie, w celu uproszczenia obliczeń.

3. **Fale i drgania**:
   Jedynka trygonometryczna jest używana do analizy ruchów harmonicznych i fal sinusoidalnych, gdzie relacje między sinusami i cosinusami są kluczowe.

4. **Geometria analityczna**:
   W geometrii analitycznej jedynka trygonometryczna pomaga w analizie kół i elips, ponieważ \(\sin^2(\theta) + \cos^2(\theta) = 1\) jest równaniem okręgu o promieniu 1.

#### Przykład w Pythonie

Możemy użyć biblioteki `numpy` w Pythonie do demonstracji jedynki trygonometrycznej.

```python
import numpy as np

# Przykładowy kąt w radianach
theta = np.pi / 4  # 45 stopni

# Obliczanie wartości sinusa i cosinusa
sin_theta = np.sin(theta)
cos_theta = np.cos(theta)

# Weryfikacja jedynki trygonometrycznej
identity = sin_theta**2 + cos_theta**2
print(f"sin^2(θ) + cos^2(θ) = {identity}")
```

Wynik powinien być bardzo bliski 1, co potwierdza jedynkę trygonometryczną.

Jedynka trygonometryczna jest fundamentem wielu innych tożsamości trygonometrycznych i znajduje szerokie zastosowanie w różnych dziedzinach matematyki oraz nauk przyrodniczych.

In [13]:
# TEORIA

### Mnożenie macierzy

Mnożenie macierzy jest operacją algebraiczną, w której dwie macierze są łączone, aby utworzyć nową macierz. Aby mnożenie macierzy było możliwe, liczba kolumn pierwszej macierzy musi być równa liczbie wierszy drugiej macierzy. Wynikowa macierz ma wymiary równe liczbie wierszy pierwszej macierzy oraz liczbie kolumn drugiej macierzy. Każdy element w wynikowej macierzy jest obliczany jako suma iloczynów odpowiadających sobie elementów wiersza pierwszej macierzy i kolumny drugiej macierzy.

### Wyznacznik macierzy

Wyznacznik macierzy (determinant) jest wartością scalarną przypisaną do kwadratowej macierzy, która może być interpretowana jako miara objętości równoległościanu rozpiętego przez wiersze (lub kolumny) macierzy. Wyznacznik macierzy \(A\) oznacza się jako \(\det(A)\) lub \(|A|\). Wyznacznik jest wykorzystywany do badania właściwości macierzy, takich jak odwracalność. Macierz jest odwracalna, jeśli jej wyznacznik jest różny od zera.

### Wartości własne i odpowiadające im wektory własne macierzy

Wartości własne (eigenvalues) i wektory własne (eigenvectors) są pojęciami używanymi do analizy macierzy kwadratowych. Wektor własny macierzy \(A\) to taki wektor \(v\), który po pomnożeniu przez macierz \(A\) daje wektor równoległy do \(v\), czyli \(A \mathbf{v} = \lambda \mathbf{v}\), gdzie \(\lambda\) to wartość własna odpowiadająca wektorowi własnemu \(\mathbf{v}\). Wartości własne i wektory własne mają kluczowe znaczenie w wielu dziedzinach, takich jak mechanika kwantowa, analiza danych czy teoria stabilności.

### Macierz kwadratowa

Macierz kwadratowa to macierz, która ma tę samą liczbę wierszy i kolumn, czyli wymiar \(n \times n\). Przykładem macierzy kwadratowej jest macierz identycznościowa (jednostkowa), która ma jedynki na głównej przekątnej i zera w pozostałych miejscach. Macierze kwadratowe odgrywają ważną rolę w algebrze liniowej, szczególnie w kontekście wyznaczników, wartości własnych i macierzy odwrotnych.

### Macierz odwrotna

Macierz odwrotna (inversematrix) macierzy \(A\) to taka macierz \(A^{-1}\), która po pomnożeniu przez \(A\) daje macierz jednostkową \(I\), czyli \(A A^{-1} = I\). Macierz \(A\) jest odwracalna wtedy i tylko wtedy, gdy jej wyznacznik jest różny od zera. Znalezienie macierzy odwrotnej jest kluczowe w rozwiązywaniu układów równań liniowych i innych problemów matematycznych.

### Ślad macierzy

Ślad macierzy (trace) to suma elementów znajdujących się na głównej przekątnej macierzy kwadratowej. Dla macierzy \(A\) ślad oznacza się jako \(\operatorname{tr}(A)\). Ślad macierzy jest używany w różnych dziedzinach matematyki i fizyki, w szczególności w teorii macierzy, mechanice kwantowej i statystyce.

### Macierz transponowana

Macierz transponowana (transposed matrix) macierzy \(A\) to macierz oznaczona jako \(A^T\), która powstaje przez zamianę miejscami wierszy i kolumn macierzy \(A\). Jeśli \(A\) jest macierzą o wymiarach \(m \times n\), to \(A^T\) będzie macierzą o wymiarach \(n \times m\). Transponowanie macierzy jest podstawową operacją w algebrze liniowej i jest używane w wielu obliczeniach matematycznych.

```python
import numpy as np

# Przykład mnożenia macierzy
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print("Mnożenie macierzy:\n", C)

# Przykład wyznacznika macierzy
det_A = np.linalg.det(A)
print("Wyznacznik macierzy A:", det_A)

# Przykład wartości własnych i wektorów własnych
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Wartości własne:", eigenvalues)
print("Wektory własne:\n", eigenvectors)

# Przykład macierzy odwrotnej
A_inv = np.linalg.inv(A)
print("Macierz odwrotna A:\n", A_inv)

# Przykład śladu macierzy
trace_A = np.trace(A)
print("Ślad macierzy A:", trace_A)

# Przykład macierzy transponowanej
A_T = A.T
print("Macierz transponowana A:\n", A_T)
```

Te podstawowe pojęcia i operacje są fundamentem algebry liniowej i mają szerokie zastosowanie w analizie danych, statystyce, inżynierii i wielu innych dziedzinach nauki i techniki.

### Przypomnienie
### Mnożenie macierzy:
$${A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}$$
A - macierz wymairu $m\ x\ n$

$$ {B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{bmatrix}}$$
B - macierz wymairu $n\ x\ p$

$$C = AB$$
C - macierz wymiaru $m\ x\ p$  
Aby móc pomnożyć dwie macierze liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy.

Mnożenie macierzy nie jest przemienne! Tzn. $$AB \neq BA$$

### Przykład 1
$ X = \begin{bmatrix}5&3\\3&9\end{bmatrix}$, $ Y= \begin{bmatrix}1\\-1\end{bmatrix} $  
$X$ macierz 2x2  
$Y$ macierz 2x1
$$Z = X \cdot Y = \begin{bmatrix}5&3\\3&9\end{bmatrix} \cdot \begin{bmatrix}1\\-1\end{bmatrix} = \begin{bmatrix}2\\-6\end{bmatrix}$$
$Z$ macierz 2x1

### Przykład 2
$X = \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix}$, $Y = \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix}$

$X$ macierz 2x3  
$Y$ macierz 3x3
$$Z = X \cdot Y =  \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix} \cdot \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix} = \begin{bmatrix}13&9&-4\\6&2&-1\end{bmatrix}$$
$Z$ macierz 2x3




### <a name='5'></a> Ćwiczenie 65

Podane są dwie dwuwymiarowe tablice numpy $A$ oraz $B$.  
$A$ - macierz wymiaru $(3, 2)$  
$B$ - macierz wymiaru $(2, 3)$

```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Dokonaj mnożenia macierzowego tablic $A$ i $B$.

__Wskazówka:__ Użyj funkcji _np.dot()_.


In [16]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])

print(A.shape)
print(B.shape)

# Rozwiązanie 1
np.dot(A, B)

(3, 2)
(2, 3)


array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

In [17]:
# Rozwiązanie 2
A.dot(B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

### Przypomnienie

### Wyznacznik macierzy:

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

#### Oznaczenia:

${\displaystyle |A|=\left|{\begin{array}{c}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{array}}\right|} $  lub  $ {\displaystyle \det A=\det {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$

#### Przykład:
${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}}$

${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}-a_{21}a_{12}a_{33}-a_{11}a_{32}a_{23}-a_{31}a_{22}a_{13}}$

${\displaystyle \det A={\begin{vmatrix}2&4\\-1&3\end{vmatrix}}=2\cdot3-4\cdot(-1)} = 6 + 4 = 10 $





### <a name='6'></a> Ćwiczenie 66
Podana jest poniższa tablica (macierz kwadratowa) $A$:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Wyznacz wyznacznik macierzy $A$.

__Wskazówka:__ Użyj funkcji _np.linalg.det()_.


In [18]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

np.linalg.det(A)

51.999999999999986

### <a name='7'></a> Ćwiczenie 67
Podana jest poniższa tablica (macierz kwadratowa) $A$:

```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Wyzancz wartości własne i odpowiadające im wektory własne macierzy $A$.

__Wskazówka:__ Użyj funkcji _np.linalg.eig()_.


In [19]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.2462 -3.      7.2462]
[[-0.6262 -0.8944  0.8902]
 [-0.3131  0.      0.4451]
 [ 0.7141  0.4472 -0.0976]]


### Przypomnienie
### Macierz odwrotna:

$A$ - macierz kwadratowa stopnia $n$. Macierz $A$ posiada macierz odwrotną, gdy istnieje macierz $B$, taka, że
$$AB = BA = I$$

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

### <a name='8'></a> Ćwiczenie 68
Podana jest poniższa tablica (macierz kwadratowa) $A$:

```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Wyznacz macierz odwrotną do macierzy $A$.

__Wskazówka:__ Użyj funkcji _np.linalg.inv()_.


In [20]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

np.linalg.inv(A)

array([[-0.2139,  0.7562,  0.2388],
       [ 0.0597,  0.0448,  0.1194],
       [ 0.0995, -0.2587, -0.1343]])

### Przypomnienie

### Ślad macierzy:

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$

#### Przykład:
$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{2}a_{ii}=a_{11}+a_{22} = 2 + 3 = 5}$

### <a name='9'></a> Ćwiczenie 69
Podana jest poniższa tablica (macierz kwadratowa) $A$:

```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Wyznacz ślad macierzy kwadratowej $A$ (suma elementów na głównej przekątnej).

__Wskazówka:__ Użyj funkcji _np.trace()_.


In [21]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

np.trace(A)

-5

### Przypomnienie
### Macierz transponowana:

Zamiana wierszy na kolumny i kolumny na wiersze.

#### Przykład 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Przykład 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$


### Ćwiczenie 69 c.d.
Dokonaj transpozycji macierzy $A$.

In [27]:
# Rozwiązanie 1
np.transpose(A)

array([[2, 4, 5, 4],
       [0, 2, 3, 2]])

In [28]:
# Rozwiązanie 2
A.T

array([[2, 4, 5, 4],
       [0, 2, 3, 2]])

### <a name='10'></a> Ćwiczenie 70
Podane są dwie dwuwymiarowe tablice numpy $A$ oraz $B$:   
$A$ - macierz wymiaru $(4, 2)$  
$B$ - macierz wymiaru $(1, 8)$

```
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
```
Przekształć tablicę $B$ tak, aby można było dokonać mnożenia macierzowego $A \cdot B$. Wykonaj to mnożenie.

__Oczekiwany wynik:__


```
array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])
```




In [29]:
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

print(A.shape)
print(B.shape)

# Rozwiązanie 1 (bez zmiany pierwotnej tablicy B)
np.dot(A, B.reshape(2, -1))

(4, 2)
(1, 8)


array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])

In [30]:
# Rozwiązanie 2 (ze zmianą)
B = B.reshape(2, -1)
np.dot(A, B)

array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])