### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.24.4'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [2]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['002', '4.99'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49']], dtype='<U32')

### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [3]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

np.argsort(A)

array([5, 2, 1, 0, 4, 3], dtype=int64)

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [10]:
A = np.random.randn(10, 8)

np.round(A, decimals=3)

array([[ 1.794,  0.581,  0.298, -1.028, -1.419,  0.19 ,  0.136,  0.608],
       [ 0.705,  0.361, -1.467,  0.893, -0.105, -0.955, -0.415, -1.399],
       [-0.344,  0.751, -0.328, -0.862, -0.258,  0.461, -1.349, -1.019],
       [ 0.127, -1.249,  1.945, -0.153, -0.907, -0.817, -0.483, -0.57 ],
       [-2.092,  1.264, -0.015, -0.027,  0.818, -1.055, -0.758,  0.457],
       [-0.064,  0.345, -0.08 , -0.241,  1.434,  1.066, -2.499,  1.48 ],
       [ 2.159,  1.232, -0.214, -0.689,  0.728, -0.619,  0.356, -0.022],
       [ 1.218, -0.389, -0.443,  0.378,  1.934,  0.081, -0.416,  0.858],
       [ 0.718, -0.951, -0.536,  1.097,  0.428, -2.47 ,  0.482,  0.926],
       [-0.838,  0.677,  1.872,  0.396, -0.626, -0.522,  0.013,  0.378]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [11]:
W = np.array([4, 5, 1])
np.roots(W)

array([-1.  , -0.25])

Dokonaj sprawdzenia.

In [12]:
print(np.polyval(W, -1))
print(np.polyval(W, -0.25))

0
0.0


### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [13]:
Q = np.array([2, 4, -5, 1])
np.roots(Q)

array([-2.91610583,  0.65388685,  0.26221898])

In [14]:
R = np.array([2, 0, -5, 1])
np.roots(R)

array([-1.67298165,  1.46961743,  0.20336421])

### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [15]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [19]:
np.polyadd(W, Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [20]:
np.polysub(W, Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [21]:
np.polymul(W, Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [22]:
np.polyadd(W, 2 * Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [23]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2024-06-10', '2024-06-11', '2024-06-12', '2024-06-13',
       '2024-06-14', '2024-06-15', '2024-06-16', '2024-06-17',
       '2024-06-18', '2024-06-19', '2024-06-20', '2024-06-21',
       '2024-06-22', '2024-06-23', '2024-06-24', '2024-06-25',
       '2024-06-26', '2024-06-27', '2024-06-28', '2024-06-29',
       '2024-06-30', '2024-07-01', '2024-07-02', '2024-07-03',
       '2024-07-04', '2024-07-05', '2024-07-06', '2024-07-07',
       '2024-07-08', '2024-07-09'], dtype='datetime64[D]')
```



In [26]:
np.arange('2024-06-10', '2024-07-10', dtype='datetime64[D]')

array(['2024-06-10', '2024-06-11', '2024-06-12', '2024-06-13',
       '2024-06-14', '2024-06-15', '2024-06-16', '2024-06-17',
       '2024-06-18', '2024-06-19', '2024-06-20', '2024-06-21',
       '2024-06-22', '2024-06-23', '2024-06-24', '2024-06-25',
       '2024-06-26', '2024-06-27', '2024-06-28', '2024-06-29',
       '2024-06-30', '2024-07-01', '2024-07-02', '2024-07-03',
       '2024-07-04', '2024-07-05', '2024-07-06', '2024-07-07',
       '2024-07-08', '2024-07-09'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2024-01', '2024-02', '2024-03'],
       ['2024-04', '2024-05', '2024-06'],
       ['2024-07', '2024-08', '2024-09'],
       ['2024-10', '2024-11', '2024-12']], dtype='datetime64[M]')
```



In [29]:
A = np.arange('2024-01', '2025-01', dtype='datetime64[M]')
A = A.reshape(-1, 3)
A

array([['2024-01', '2024-02', '2024-03'],
       ['2024-04', '2024-05', '2024-06'],
       ['2024-07', '2024-08', '2024-09'],
       ['2024-10', '2024-11', '2024-12']], dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [30]:
np.datetime64('today')

numpy.datetime64('2024-06-01')