### NumPy - biblioteka do obliczeń numerycznych

- Podstawy obliczeń numerycznych
- Porównanie szybkości z czystym Pythonem
- Kluczowe różnice pomiędzy tablicami Numpy i listami pythonowymi
- Typowe operacje na wektorach i macierzach
- Algebra liniowa

**NumPy**, czyli **Numerical Python**, to biblioteka programistyczna w języku Python, która dostarcza wsparcie dla efektywnych operacji numerycznych, zwłaszcza na dużych tablicach i macierzach danych. Jest jednym z podstawowych narzędzi w dziedzinie naukowych obliczeń i analizy danych w języku Python.

Główne cechy i funkcje biblioteki NumPy:

1. Tablice wielowymiarowe: NumPy wprowadza nowy typ danych, znany jako **"array" (tablica)**, który pozwala na przechowywanie i operowanie danymi wielowymiarowymi. Tablice w NumPy są bardziej wydajne niż standardowe listy w Pythonie i pozwalają na efektywne wykonywanie operacji matematycznych i statystycznych na danych.

2. Efektywne operacje numeryczne: NumPy dostarcza wiele wbudowanych funkcji i operacji, takich jak **dodawanie, mnożenie, podnoszenie do potęgi, funkcje trygonometryczne itp.**, które działają efektywnie na dużych zbiorach danych.

3. Indeksowanie i wycinanie: NumPy oferuje zaawansowane możliwości indeksowania i wycinania danych z tablic, co pozwala na dostęp do konkretnych elementów lub podtablic z dużą precyzją.

4. Losowanie liczb: Biblioteka umożliwia generowanie losowych liczb o różnych rozkładach, co jest przydatne w symulacjach i analizach statystycznych.

5. Integracja z innymi bibliotekami: NumPy jest często używany w połączeniu z innymi bibliotekami do naukowych obliczeń i analizy danych, takimi jak SciPy, pandas, matplotlib i scikit-learn.

6. Obsługa danych brakujących: NumPy ma wbudowane funkcje do pracy z danymi brakującymi, co jest istotne w analizie danych.

## NumPy

Dokumentacja: [https://NumPy.org/doc/](https://NumPy.org/doc/)

Biblioteka do przetwarzania numerycznego dużych wielowymiarowych tablic liczbowych. 

Typowy import:

- Strona biblioteki: https://numpy.org/
- Dokumentacja: https://numpy.org/doc/
-  ---

- Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:

```python
pip install numpy
```

In [1]:
!pip install numpy

In [4]:
import numpy as np
np.__version__

'1.24.3'

## `np.ndarray`


* Reprezentuje jedno lub wielowymiarową tablicę wartości. Jest to podstawowa klasa definiowana przez bibliotekę.
* Wszystkie wartości w tablicy musza być tego samego typu, czyli `np.ndarray` jest tablicą jednorodną (homogeniczną) .
* Każda wartość zajmuje tę samą określoną przez typ porcję pamięci.

## `np.array()`

Tworzy tablice z "tablicopodobnych" obiektów, np. z list:

In [13]:
lista_pythonowa = [1,2,'3',[1]]
lista_pythonowa

[1, 2, '3', [1]]

In [26]:
a = np.array([1,2,3])

In [28]:
a

array([1, 2, 3])

In [21]:
print(a)

[1 2 3]


In [20]:
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [29]:
a.dtype

dtype('int32')

Automatyczne rozszerzanie typu:

In [30]:
a = np.array([1.5, 2, 3.14])
a.dtype

dtype('float64')

In [31]:
a

array([1.5 , 2.  , 3.14])

In [32]:
a = np.array([1, 2, 3], dtype='float64')
a

array([1., 2., 3.])

## NumPy: typy wbudowane

Data type |Description
---|---
bool_ |Boolean (True or False) stored as a byte
int_ |Default integer type (same as C long; normally either int64 or int32)
intc |Identical to C int (normally int32 or int64)
intp |Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8 |Byte (-128 to 127)
int16 |Integer (-32768 to 32767)
int32 |Integer (-2147483648 to 2147483647)
int64 |Integer (-9223372036854775808 to 9223372036854775807)
uint8 |Unsigned integer (0 to 255)
uint16 |Unsigned integer (0 to 65535)
uint32 |Unsigned integer (0 to 4294967295)
uint64 |Unsigned integer (0 to 18446744073709551615)
float_ |Shorthand for float64.
float16 |Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 |Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 |Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_ |Shorthand for complex128.
complex64 |Complex number, represented by two 32-bit floats
complex128 |Complex number, represented by two 64-bit floats

## Dygresja: pamięć zajmowana przez tablicę
### `np.nbytes`

Liczba bajtów zajęta przez jedną wartość danego typu:

In [33]:
np.nbytes

{numpy.bool_: 1,
 numpy.int8: 1,
 numpy.uint8: 1,
 numpy.int16: 2,
 numpy.uint16: 2,
 numpy.intc: 4,
 numpy.uintc: 4,
 numpy.int64: 8,
 numpy.uint64: 8,
 numpy.int32: 4,
 numpy.uint32: 4,
 numpy.float16: 2,
 numpy.float32: 4,
 numpy.float64: 8,
 numpy.longdouble: 8,
 numpy.complex64: 8,
 numpy.complex128: 16,
 numpy.clongdouble: 16,
 numpy.object_: 8,
 numpy.bytes_: 0,
 numpy.str_: 0,
 numpy.void: 0,
 numpy.datetime64: 8,
 numpy.timedelta64: 8}

In [34]:
a = np.array([[1, 2, 3]])
a

array([[1, 2, 3]])

In [35]:
a.dtype

dtype('int32')

`a.itemsize` -- wspólny rozmiar w bajtach pojedynczej wartości w tablicy `a`:

In [36]:
a.itemsize

4

### `.nbytes`

Liczba bajtów zajętych przez wartości tablicy:

In [37]:
a.nbytes

12

 - `itemsize` zwraca rozmiar (w bajtach) jednego elementu tablicy NumPy.
 - `nbytes` zwraca całkowitą ilość pamięci (w bajtach), jaką zajmuje tablica NumPy.
 - Funkcja `sys.getsizeof()` zwraca rozmiar (w bajtach) obiektu w Pythonie, obejmujący wewnętrzne struktury pamięci obiektu. Jest używana do sprawdzenia, ile pamięci zajmuje obiekt Pythonowy, wliczając narzut związany z zarządzaniem pamięcią przez Python.

### `sys.getsizeof()`

Zwraca wielkość obiektu w bajtach:

In [39]:
a = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(a.itemsize)  # Wyjście: 4 (każdy element zajmuje 4 bajty)

4


In [40]:
import sys

In [41]:
sys.getsizeof(1)

28

In [42]:
sys.getsizeof([1, 2, 3, 4, 5])

120

In [44]:
2**100

1267650600228229401496703205376

In [43]:
sys.getsizeof(2**100)

40

In [45]:
np.array(2**100).itemsize

8

In [46]:
sys.getsizeof(a)

132

Metadane tablicy nieznacznie zwiększają jej rzeczywisty rozmiar:

In [47]:
print('{:<25}{:<15}{:<10}'.format('Tablica', 'Mem wartości', 'Mem obiektu'))

for k in range(6):
    a = np.array(range(k))
    print('{!r:<25}{:<15}{:<10}'.format(a, a.nbytes, sys.getsizeof(a)))

Tablica                  Mem wartości   Mem obiektu
array([], dtype=float64) 0              112       
array([0])               4              116       
array([0, 1])            8              120       
array([0, 1, 2])         12             124       
array([0, 1, 2, 3])      16             128       
array([0, 1, 2, 3, 4])   20             132       


In [49]:
a.nbytes

20

In [51]:
a = np.array(range(2000))
a

array([   0,    1,    2, ..., 1997, 1998, 1999])

In [52]:
a.itemsize

4

In [53]:
a.nbytes

8000

In [54]:
sys.getsizeof(a)

8112

##### dla listy w Python:

In [55]:
l = []
for i in range(2000):
    l.append(i)
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [56]:
sys.getsizeof(l)

16184

In [57]:
sys.getsizeof(l) + sum(sys.getsizeof(item) for item in l)

72180

### Poprawne porównanie rozmiarów

Aby porównać rozmiar zajmowanej pamięci przez listę i tablicę NumPy, powinniśmy użyć odpowiednich metod:
- **Dla listy**: `sys.getsizeof(python_list) + sum(sys.getsizeof(item) for item in python_list)`
- **Dla tablicy NumPy**: `sys.getsizeof(numpy_array)` dla samego obiektu oraz `numpy_array.nbytes` dla danych.

### Wyniki i wyjaśnienie

- **Lista Pythona**:
  - `sys.getsizeof(python_list)`: rozmiar samej listy (narzut pamięciowy struktury listy).
  - `sum(sys.getsizeof(item) for item in python_list)`: rozmiar wszystkich elementów (każdy element jest oddzielnym obiektem Pythona).

- **Tablica NumPy**:
  - `sys.getsizeof(numpy_array)`: narzut obiektu tablicy NumPy.
  - `numpy_array.nbytes`: całkowity rozmiar danych przechowywanych w tablicy.

Tablica NumPy będzie zazwyczaj bardziej efektywna pamięciowo niż lista Pythona ze względu na brak dodatkowego narzutu związanego z zarządzaniem indywidualnymi obiektami elementów.

W Pythonie lista jest strukturą danych, która przechowuje referencje do obiektów, a nie same obiekty. Dlatego całkowita pamięć zajmowana przez listę obejmuje zarówno narzut związany z samą listą, jak i pamięć zajmowaną przez poszczególne elementy, do których lista odwołuje się przez referencje.

### Morał

Nawet proste wbudowane typy w Pythonie są złożonymi obiektami zawierającymi liczne dodatkowe dane. Dlatego zwykła lista obiektów ma duży rozmiar i skomplikowaną strukturę.

Tablica NumPy odpowiada tablicy w języku C. Ma prostą strukturę, zajmuje jednorodny obszar pamięci, a wartości nie zawierają żadnych dodatkowych metadanych.

In [58]:
a

array([   0,    1,    2, ..., 1997, 1998, 1999])

## Atrybuty tablic

* `.ndim` -- liczba wymiarów, liczba całkowita.
* `.shape` -- rozmiar każdego z wymiarów, krotka liczb całkowitych.
* `.size` -- całkowita liczba wartości, iloczyn wartości z krotki `.shape`.

In [59]:
a.ndim

1

In [60]:
a.shape

(2000,)

In [61]:
a.size

2000

## Tworzenie tablic z niczego

* `np.zeroes()`
* `np.ones()`
* `np.full()`
* `np.arange()`
* `np.linspace()`
* `np.random.random()`
* `np.random.normal()`
* `np.random.randint()`
* `np.eye()`
* i inne ...

In [65]:
np.ones((30,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])